### ISSUE TITLE
[BUG] Nvidia gpu not usuable

### ISSUE THREAD

**Issue by DrFatalis** [linuxserver/docker-mullvad-browser#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Docker compose file grants permission to use my Nvidia GPU GTX1050TI (driver 530) --> working with frigate container
From the container shell, nvidia-smi is working but shows 0 process. 

When starting mullvad-browser container, logs are showing a problem with the libGL

### Expected Behavior

It is expected that the container starts with no error message and i assume here that a process should be shown in the nvidia-smi output. 

### Steps To Reproduce

Simply use the docker-compose file and starts it.

### Environment

```markdown
- OS:Ubuntu 22.04.2
- How docker service was installed:distro's packagemanager
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
mullvad-browser:
image: lscr.io/linuxserver/mullvad-browser:latest
container_name: mullvad-browser
hostname: mullvad-browser
mem_limit: 1024m
cap_add:
 - NET_ADMIN
security_opt:
 - seccomp:unconfined #optional
runtime: nvidia
deploy:
resources:
reservations:
devices:
 - driver: nvidia
count: 1 # number of GPUs
capabilities: [gpu]
devices:
 - /dev/dri:/dev/dri
environment:
 - PUID=1000
 - PGID=1000
 - TZ=Europe/Paris
 - LOCAL_NET=192.168.0.0/16 #optional
 - NVIDIA_VISIBLE_DEVICES=GPU-xxxxxxx
 - NVIDIA_DRIVER_CAPABILITIES=all
 - DRINODE=/dev/dri/renderD128
volumes:
 - ~/config:/config
networks:
 - traefik-net
ports:
 - 4000:3000
 - 4001:3001
shm_size: "1gb"
labels:
 - "com.centurylinklabs.watchtower.enable=true"
 - "traefik.docker.network=web"
 - traefik.enable=true
 - traefik.http.routers.mullvad.rule=Host(`xxxxxxxxx`)
 - traefik.http.routers.mullvad.priority=1
 - traefik.http.routers.mullvad.tls=true
 - traefik.http.routers.mullvad.tls.certresolver=lets-encrypt
 - traefik.http.routers.mullvad.middlewares=authelia@docker
 - traefik.http.services.mullvad.loadbalancer.server.port=3000
restart: always

networks:
traefik-net:
name: web
external: true
```

### Container logs

```bash
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
**** permissions for /dev/dri/renderD128 are good ****
**** permissions for /dev/dri/card0 are good ****
Uname info: Linux mullvad-browser 5.19.0-40-generic #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
[custom-init] No custom files found, skipping...
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
Xvnc KasmVNC 1.1.0 - built Apr 19 2023 17:28:36
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add xxxx/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
Obt-Message: Xinerama extension is not present on the server
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
sysctl: setting key "net.ipv4.conf.all.src_valid_mark", ignoring: Read-only file system
[#] iptables-restore -n
[#] DROUTE=$(ip route | grep default | awk '{print $3}'); HOMENET=192.168.x.x/16; HOMENET2=10.x.x.x/8; HOMENET3=172.x.x.x/8; ip route add $HOMENET3 via $DROUTE;ip route add $HOMENET2 via $DROUTE; ip route add $HOMENET via $DROUTE;iptables -I OUTPUT -d $HOMENET -j ACCEPT;iptables -A OUTPUT -d $HOMENET2 -j ACCEPT; iptables -A OUTPUT -d $HOMENET3 -j ACCEPT;  iptables -A OUTPUT ! -o wg0 -m mark ! --mark $(wg show wg0 fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
[ls.io-init] done.
mkdir: cannot create directory ‘/config/lsio’: File exists
libGL error: glx: failed to create dri3 screen
libGL error: failed to load driver: nouveau
```

**Comment by aptalca** [comment]
Remove Nvidia driver injection. Kasmvnc does not work with. It only works with the open source drivers that are included. Only map /dev/dri

**Comment by DrFatalis** [comment]
I changed my docker-compose file to: 

`version: "2.1"
services:
mullvad-browser:
image: lscr.io/linuxserver/mullvad-browser:latest
container_name: mullvad-browser
hostname: mullvad-browser
mem_limit: 1024m
cap_add:
 - NET_ADMIN
security_opt:
 - seccomp:unconfined #optional
devices:
 - /dev/dri:/dev/dri
environment:
 - PUID=1000
 - PGID=1000
 - TZ=Europe/Paris
 - LOCAL_NET=192.168.0.0/16 #optional
 - DRINODE=/dev/dri/renderD128
volumes:
 - ~/config:/config
networks:
 - traefik-net
ports:
 - 4000:3000
 - 4001:3001
shm_size: "1gb"
labels:
 - "com.centurylinklabs.watchtower.enable=true"
 - "traefik.docker.network=web"
 - traefik.enable=true
 - traefik.http.routers.mullvad.rule=Host(`xxxxxxxxx`)
 - traefik.http.routers.mullvad.priority=1
 - traefik.http.routers.mullvad.tls=true
 - traefik.http.routers.mullvad.tls.certresolver=lets-encrypt
 - traefik.http.routers.mullvad.middlewares=authelia@docker
 - traefik.http.services.mullvad.loadbalancer.server.port=3000
restart: always

networks:
traefik-net:
name: web
external: true`

The logs are similar but /dev/dri now have ids

`**** adding /dev/dri/renderD128 to video group render with id 109 ****
**** adding /dev/dri/card0 to video group video with id 44 ****`

however I still have libGL errors after the VPN connection

`mkdir: cannot create directory ‘/config/lsio’: File exists
[ls.io-init] done.
libGL error: glx: failed to create dri3 screen
libGL error: failed to load driver: nouveau`

**Comment by thelamer** [comment]
GLX/EGL does not work with nvidia's closed source driver as it lacks DRI3 and uses a proprietary dri interface. 
This is noted in the readme: 
https://github.com/linuxserver/docker-mullvad-browser#optional-run-configurations
You cannot have the proprietary driver host level, you would need to switch to nouveau which I would assume you would not want to do. 
It just is what it is, hopefully with the new NVK nouveau things will pick up on the open source side. 
You can still mount an NVIDIA GPU into the container using the runtime, it will just only work with backend stuff like cuda and transcoding.

**Comment by DrFatalis** [comment]
understood ! thank you for the explanation
